/**
 * Detect GFM tables inside a markdown string and normalize every column to a
 * uniform width by padding cells with spaces.
 *
 * - Skips fenced code blocks (``` / ~~~) so example tables stay untouched.
 * - Handles escaped pipes (\|), optional leading/trailing pipes, ragged rows.
 * - Preserves alignment markers (:---, ---:, :---:) in the delimiter row.
 * - Measures width by code point, counting East Asian wide chars as 2.
 *
 * Generated by claude.ai
 */

const FENCE_RE = /^ {0,3}(`{3,}|~{3,})/;
const DELIM_CELL_RE = /^:?-+:?$/;

const WIDE_RE =
  /^(?:[\u1100-\u115F\u2E80-\u303E\u3041-\u33FF\u3400-\u4DBF\u4E00-\u9FFF\uA000-\uA4CF\uAC00-\uD7A3\uF900-\uFAFF\uFE10-\uFE19\uFE30-\uFE6F\uFF00-\uFF60\uFFE0-\uFFE6]|[\u{1F300}-\u{1F64F}]|[\u{1F900}-\u{1F9FF}]|[\u{1F680}-\u{1F6FF}]|[\u{20000}-\u{3FFFD}])$/u;

const ZERO_WIDTH_RE =
  /^(?:[\p{Mn}\p{Me}]|[\u200B-\u200F\u2060\uFEFF]|[\u{E0100}-\u{E01EF}]|\u{FE0F})$/u;

/** Visual width of a string in monospace columns. */
export function stringWidth(str) {
  let width = 0;
  for (const char of str) {
    if (ZERO_WIDTH_RE.test(char)) continue;
    width += WIDE_RE.test(char) ? 2 : 1;
  }
  return width;
}

/** Split a table row into trimmed cells, respecting `\|` escapes. */
function splitRow(line) {
  const text = line.trim();
  const cells = [];
  let cell = "";
  let endsWithPipe = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (char === "\\" && text[i + 1] === "|") {
      cell += "\\|";
      i++;
      endsWithPipe = false;
    } else if (char === "|") {
      cells.push(cell);
      cell = "";
      endsWithPipe = true;
    } else {
      cell += char;
      endsWithPipe = false;
    }
  }
  cells.push(cell);

  if (text.startsWith("|")) cells.shift();
  if (endsWithPipe && cells.length) cells.pop();

  return cells.map((c) => c.trim());
}

function hasUnescapedPipe(line) {
  return /(?<!\\)\|/.test(line);
}

/** Read the alignment of each delimiter cell, or null if it isn't a delimiter row. */
function parseDelimiters(line) {
  if (!hasUnescapedPipe(line)) return null;
  const cells = splitRow(line);
  if (!cells.length || !cells.every((c) => DELIM_CELL_RE.test(c))) return null;
  return cells.map((c) => {
    const left = c.startsWith(":");
    const right = c.endsWith(":");
    if (left && right) return "center";
    if (right) return "right";
    if (left) return "left";
    return null;
  });
}

/** Try to read a table starting at `start`. Returns null when there is none. */
function readTable(lines, start) {
  const header = lines[start];
  if (header === undefined || !hasUnescapedPipe(header)) return null;

  const alignments = parseDelimiters(lines[start + 1] ?? "");
  if (!alignments) return null;

  const headerCells = splitRow(header);
  if (headerCells.length !== alignments.length) return null;

  const rows = [headerCells];
  let end = start + 1;
  for (let i = start + 2; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim() || !hasUnescapedPipe(line)) break;
    rows.push(splitRow(line));
    end = i;
  }

  const indent = header.match(/^[ \t]*/)[0];
  return { rows, alignments, indent, start, end };
}

function padCell(text, target, alignment, width) {
  const gap = Math.max(0, target - width(text));
  if (alignment === "right") return " ".repeat(gap) + text;
  if (alignment === "center") {
    const left = Math.floor(gap / 2);
    return " ".repeat(left) + text + " ".repeat(gap - left);
  }
  return text + " ".repeat(gap);
}

function buildDelimiter(target, alignment) {
  if (alignment === "center") return `:${"-".repeat(Math.max(1, target - 2))}:`;
  if (alignment === "right") return `${"-".repeat(Math.max(2, target - 1))}:`;
  if (alignment === "left") return `:${"-".repeat(Math.max(2, target - 1))}`;
  return "-".repeat(Math.max(3, target));
}

function renderTable(table, { align, minWidth, width }) {
  const { rows, alignments, indent } = table;
  const columns = Math.max(alignments.length, ...rows.map((r) => r.length));

  const widths = Array.from({ length: columns }, (_, col) => {
    const longest = Math.max(0, ...rows.map((row) => width(row[col] ?? "")));
    return Math.max(minWidth, longest);
  });

  const line = (cells, isDelimiter) =>
    `${indent}| ${widths
      .map((target, col) =>
        isDelimiter
          ? buildDelimiter(target, alignments[col])
          : padCell(
              cells[col] ?? "",
              target,
              align ? alignments[col] : "left",
              width,
            ),
      )
      .join(" | ")} |`;

  return [
    line(rows[0], false),
    line(null, true),
    ...rows.slice(1).map((row) => line(row, false)),
  ];
}

/**
 * Normalize the column widths of every markdown table in a string.
 *
 * @param {string} markdown
 * @param {object} [options]
 * @param {boolean} [options.align=false]   Pad according to the table's own
 *                                          alignment markers instead of always
 *                                          padding on the right.
 * @param {number}  [options.minWidth=3]    Minimum column width.
 * @param {(s: string) => number} [options.width=stringWidth]
 *                                          Custom width function — swap in the
 *                                          `string-width` package for full
 *                                          Unicode/emoji correctness.
 * @returns {string}
 */
export function formatMarkdownTables(markdown, options = {}) {
  const { align = false, minWidth = 3, width = stringWidth } = options;
  const eol = markdown.includes("\r\n") ? "\r\n" : "\n";
  const lines = markdown.split(/\r?\n/);
  const out = [];
  let fence = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const fenceMatch = line.match(FENCE_RE);

    if (fence) {
      out.push(line);
      if (
        fenceMatch &&
        fenceMatch[1][0] === fence[0] &&
        fenceMatch[1].length >= fence.length
      ) {
        fence = null;
      }
      continue;
    }
    if (fenceMatch) {
      fence = fenceMatch[1];
      out.push(line);
      continue;
    }

    const table = readTable(lines, i);
    if (!table) {
      out.push(line);
      continue;
    }
    out.push(...renderTable(table, { align, minWidth, width }));
    i = table.end;
  }

  return out.join(eol);
}

export default formatMarkdownTables;
